import i18n from '@i18n';

import { STRIPE_ORGANIZATION_PRODUCT_ID, STRIPE_COMMUNITY_PRODUCT_ID } from '@const/stripe';

export interface IProductFeatures {
  id?: string
  title: string
  description: string
  productType: string
  name: string
  votingPerYear: number
  processes: number
  administrators: number,
  freePlan: boolean
  list: FeatureName[]
}

export enum FeatureName {
  VotingSimpleProcess = 'voting-simple-process',
  VotingMultipleAnswers = 'voting-multiple-answers',
  VotingAnonymous = 'voting-anonymous',
  VotingAbstainFromAnswer = 'voting-abstain-from-answer',
  VotingStepByStep = 'voting-step-by-step',
  VotingEndToEndVerifiability = 'voting-end-to-end-verifiability',
  VotingTamperProof = 'voting-tamper-proof',
  VotingIntegrityBlockchain = 'voting-integrity-blockchain',
  VotingQuestionByQuestion = 'voting-question-by-question',
  VotingRealtime = 'voting-realtime',
  VotingQuadratic = 'voting-quadratic',
  VotingDigitalCertificate = 'voting-digital-certificate',
  AGMSaveDraft = 'agm-save-draft',
  AGMTestVotingProcess = 'agm-test-voting-process',
  AGMRealtimeQA = 'agm-realtime-qa',
  AGMVideoConference = 'agm-video-conference',
  AGMStreaming = 'agm-streaming',
  PaymentsAcceptPayments = 'payments-accept-payments',
  PaymentsDonationButton = 'payments-donation-button',
  CensusUploadCSV = 'census-upload-csv',
  CensusTagging = 'census-tagging',
  CensusSegmentation = 'census-segmentation',
  InsightsVotingResults = 'insights-voting-results',
  InsightsBasicAnalytics = 'insights-basic-analytics',
  InsightsAdvancedAnalytics = 'insights-advanced-analytics',
  InsightsDownloadPDF = 'insights-download-pdf',
  BrandingCustomLogo = 'branding-custom-logo',
  BrandingRemoveVocdoniBranding = 'branding-remove-vocdoni-branding',
  BrandingCustomColors = 'branding-custom-colors',
  BrandingCustomSubdomain = 'branding-custom-subdomain',
  CommunicationsVotingCalendar = 'communications-voting-calendar',
  CommunicationsVotingEmail = 'communications-voting-email',
  CommunicationMewsFeed = 'communication-mews-feed',
  IntegrationsZappier = 'integrations-zappier',
  IntegrationsMamilchimp = 'integrations-mailchimp',
  IntegrationsCRM = 'integrations-crm',
  SupportLiveChat = 'support-live-chat',
  SupportPrioritySupport = 'support-priority-support',
  SupportManagedProcess = 'support-managed-process',
  SupportDedicatedAgentSupport = 'support-dedicated-agent-support',
}
export const UNLIMITED = -1

export const productsFeatures: IProductFeatures[] = [
  {
    title: i18n.t('products.plans.basic.title'),
    description: i18n.t('products.plans.basic.description'),
    name: "test",
    productType: "basic",
    votingPerYear: UNLIMITED,
    freePlan: true,
    processes: 5,
    administrators: 1,
    list: [
      FeatureName.VotingSimpleProcess,
      FeatureName.VotingMultipleAnswers,
      FeatureName.VotingAnonymous,
      FeatureName.VotingAbstainFromAnswer,
      FeatureName.VotingStepByStep,
      FeatureName.VotingEndToEndVerifiability,
      FeatureName.VotingTamperProof,
      FeatureName.AGMSaveDraft,
      FeatureName.PaymentsAcceptPayments,
      FeatureName.PaymentsDonationButton,
      FeatureName.CensusUploadCSV,
      FeatureName.InsightsVotingResults,
      FeatureName.InsightsAdvancedAnalytics,
      FeatureName.CommunicationsVotingCalendar,
      FeatureName.CommunicationMewsFeed,
      FeatureName.SupportLiveChat,
    ]
  },
  {
    id: STRIPE_ORGANIZATION_PRODUCT_ID,
    title: i18n.t('products.plans.organization.title'),
    description: i18n.t('products.plans.organization.description'),
    name: "Vocdoni Premium",
    productType: "organization",
    votingPerYear: UNLIMITED,
    processes: UNLIMITED,
    administrators: 5,
    freePlan: false,
    list: [
      FeatureName.VotingSimpleProcess,
      FeatureName.VotingMultipleAnswers,
      FeatureName.VotingAnonymous,
      FeatureName.VotingAbstainFromAnswer,
      FeatureName.VotingStepByStep,
      FeatureName.VotingEndToEndVerifiability,
      FeatureName.VotingTamperProof,
      FeatureName.VotingQuestionByQuestion,
      FeatureName.VotingRealtime,
      FeatureName.VotingQuadratic,
      FeatureName.VotingDigitalCertificate,
      FeatureName.VotingIntegrityBlockchain,
      FeatureName.AGMSaveDraft,
      FeatureName.AGMTestVotingProcess,
      FeatureName.AGMRealtimeQA,
      FeatureName.AGMVideoConference,
      FeatureName.AGMStreaming,
      FeatureName.PaymentsAcceptPayments,
      FeatureName.PaymentsDonationButton,
      FeatureName.CensusUploadCSV,
      FeatureName.CensusTagging,
      FeatureName.InsightsVotingResults,
      FeatureName.InsightsBasicAnalytics,
      FeatureName.InsightsDownloadPDF,
      FeatureName.BrandingCustomLogo,
      FeatureName.BrandingRemoveVocdoniBranding,
      FeatureName.BrandingCustomColors,
      FeatureName.CommunicationsVotingCalendar,
      FeatureName.CommunicationMewsFeed,
      FeatureName.CommunicationsVotingEmail,
      FeatureName.IntegrationsZappier,
      FeatureName.IntegrationsMamilchimp,
      FeatureName.IntegrationsCRM,
      FeatureName.SupportLiveChat,
      FeatureName.SupportPrioritySupport,
    ]
  },
  {
    id: STRIPE_COMMUNITY_PRODUCT_ID,
    title: i18n.t('products.plans.community.title'),
    description: i18n.t('products.plans.community.description'),
    name: "Vocdoni Premium",
    productType: "community",
    votingPerYear: UNLIMITED,
    processes: UNLIMITED,
    administrators: 2,
    freePlan: false,
    list: [
      FeatureName.VotingSimpleProcess,
      FeatureName.VotingMultipleAnswers,
      FeatureName.VotingAnonymous,
      FeatureName.VotingAbstainFromAnswer,
      FeatureName.VotingStepByStep,
      FeatureName.VotingEndToEndVerifiability,
      FeatureName.VotingTamperProof,
      FeatureName.VotingQuestionByQuestion,
      FeatureName.VotingRealtime,
      FeatureName.VotingQuadratic,
      FeatureName.VotingDigitalCertificate,
      FeatureName.VotingIntegrityBlockchain,
      FeatureName.AGMSaveDraft,
      FeatureName.AGMTestVotingProcess,
      FeatureName.AGMRealtimeQA,
      FeatureName.AGMVideoConference,
      FeatureName.AGMStreaming,
      FeatureName.PaymentsAcceptPayments,
      FeatureName.PaymentsDonationButton,
      FeatureName.CensusUploadCSV,
      FeatureName.CensusTagging,
      FeatureName.CensusSegmentation,
      FeatureName.InsightsVotingResults,
      FeatureName.InsightsBasicAnalytics,
      FeatureName.InsightsAdvancedAnalytics,
      FeatureName.InsightsDownloadPDF,
      FeatureName.BrandingCustomLogo,
      FeatureName.BrandingRemoveVocdoniBranding,
      FeatureName.BrandingCustomColors,
      FeatureName.BrandingCustomSubdomain,
      FeatureName.CommunicationsVotingCalendar,
      FeatureName.CommunicationMewsFeed,
      FeatureName.CommunicationsVotingEmail,
      FeatureName.IntegrationsZappier,
      FeatureName.IntegrationsMamilchimp,
      FeatureName.IntegrationsCRM,
      FeatureName.SupportLiveChat,
      FeatureName.SupportPrioritySupport,
      FeatureName.SupportManagedProcess,
      FeatureName.SupportDedicatedAgentSupport,
    ]
  },
]