export const CREATE_ENTITY_PATH = '/entities/new'
export const CREATE_PROPOSAL_PATH = '/votes/new'
export const DASHBOARD_PATH = '/dashboard'
export const SIGN_IN_PATH = '/login'
export const FORGOT_PASSPHRASE_PATH = '/login'
export const PRICING_PATH = '/pricing'
export const ABOUT_PATH = '/about'
export const VOTING_AUTH_FORM_PATH = '/votes/auth/form'
