export const CREATE_ENTITY_PATH = '/entities/new'
export const CREATE_PROPOSAL_PATH = '/votes/new'
export const DASHBOARD_PATH = '/dashboard'
export const SIGN_IN_PATH = '/login'
export const FORGOT_PASSPHRASE_PATH = '/login'
